version: '3.8'

services:
  backend:
    build: ./backend
    # command: gunicorn makeeasyhmis.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    
    networks:
      - mkis   

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mks

    networks:
      - mkis  

  frontend:
    container_name: frontend
    build:
      context: ./front-end
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - backend  

    networks:
      - mkis

networks:
  mkis:
    driver: bridge      

volumes:
  postgres_data: